-- 코드를 입력하세요
SELECT J.FLAVOR
FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS J_TOTAL
     FROM JULY
     GROUP BY FLAVOR) J
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS F_TOTAL
     FROM FIRST_HALF
     GROUP BY FLAVOR) F ON J.FLAVOR = F.FLAVOR
ORDER BY J_TOTAL + F_TOTAL DESC
LIMIT 3