SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, (SELECT SUM(CODE) AS CODE
                    FROM SKILLCODES
                    WHERE NAME LIKE 'C#' OR NAME LIKE 'Python') C
WHERE D.SKILL_CODE & C.CODE
ORDER BY D.ID